steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', "pwd;ls -l /workspace/tasknote-web/"]
  dir: '/workspace'
- name: node
  entrypoint: yarn
  args: ['install']
  dir: 'tasknote-web/'
- name: node
  entrypoint: yarn
  args: ['run', 'build']
  dir: 'tasknote-web/'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', "pwd;ls -l /workspace/tasknote-web/"]
  dir: '/workspace'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', "pwd;cp -R /workspace/tasknote-web/dist/* /workspace/tasknote-api/src/main/resources/META-INF/resources/"]
  dir: '/workspace'
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'tasknote-api/'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tasknote-mono', '-f', 'src/main/docker/Dockerfile.jvm', '.']
  dir: 'tasknote-api/'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tasknote-mono']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'tasknote-mono', 
  '--image', 'gcr.io/$PROJECT_ID/tasknote-mono', 
  '--region', 'us-central1', 
  '--platform', 'managed', 
  '--allow-unauthenticated',
  '--service-account', 'toolbox@toolbox-289508.iam.gserviceaccount.com'
  ]

images:
- gcr.io/$PROJECT_ID/tasknote-mono