steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tasknotes', '-f', 'src/main/docker/Dockerfile.jvm', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tasknotes']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'tasknote', 
  '--image', 'gcr.io/$PROJECT_ID/tasknotes', 
  '--region', 'us-central1', 
  '--platform', 'managed', 
  '--allow-unauthenticated',
  '--set-env-vars', 'TASKNOTES_GCP_PROJECT=$PROJECT_ID,TASKNOTES_GCP_BUCKET_IMAGE=${_BUCKET_IMAGE},TASKNOTES_GCP_BUCKET_DATA=${_BUCKET_DATA},MP_JWT_VERIFY_ISSUER=${_GCP_JWT_ISSUER},QUARKUS_HTTP_CORS_ORIGINS=${_CORS_ORIGIN}',
  '--service-account', '${_SRV_ACCOUNT}'
  ]
images:
- gcr.io/$PROJECT_ID/tasknotes